# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wp_global.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import error_pb2 as error__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='wp_global.proto',
  package='wirepas.proto.gateway_api',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0fwp_global.proto\x12\x19wirepas.proto.gateway_api\x1a\x0b\x65rror.proto\"0\n\rRequestHeader\x12\x0e\n\x06req_id\x18\x01 \x02(\x04\x12\x0f\n\x07sink_id\x18\x02 \x01(\t\"s\n\x0eResponseHeader\x12\x0e\n\x06req_id\x18\x01 \x02(\x04\x12\r\n\x05gw_id\x18\x02 \x02(\t\x12\x0f\n\x07sink_id\x18\x03 \x01(\t\x12\x31\n\x03res\x18\x04 \x02(\x0e\x32$.wirepas.proto.gateway_api.ErrorCode\"?\n\x0b\x45ventHeader\x12\r\n\x05gw_id\x18\x01 \x02(\t\x12\x0f\n\x07sink_id\x18\x02 \x01(\t\x12\x10\n\x08\x65vent_id\x18\x03 \x02(\x04\"K\n\x0f\x46irmwareVersion\x12\r\n\x05major\x18\x01 \x02(\r\x12\r\n\x05minor\x18\x02 \x02(\r\x12\r\n\x05maint\x18\x03 \x02(\r\x12\x0b\n\x03\x64\x65v\x18\x04 \x02(\r*\x1d\n\nOnOffState\x12\x06\n\x02ON\x10\x01\x12\x07\n\x03OFF\x10\x02')
  ,
  dependencies=[error__pb2.DESCRIPTOR,])

_ONOFFSTATE = _descriptor.EnumDescriptor(
  name='OnOffState',
  full_name='wirepas.proto.gateway_api.OnOffState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ON', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OFF', index=1, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=368,
  serialized_end=397,
)
_sym_db.RegisterEnumDescriptor(_ONOFFSTATE)

OnOffState = enum_type_wrapper.EnumTypeWrapper(_ONOFFSTATE)
ON = 1
OFF = 2



_REQUESTHEADER = _descriptor.Descriptor(
  name='RequestHeader',
  full_name='wirepas.proto.gateway_api.RequestHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='req_id', full_name='wirepas.proto.gateway_api.RequestHeader.req_id', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sink_id', full_name='wirepas.proto.gateway_api.RequestHeader.sink_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=107,
)


_RESPONSEHEADER = _descriptor.Descriptor(
  name='ResponseHeader',
  full_name='wirepas.proto.gateway_api.ResponseHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='req_id', full_name='wirepas.proto.gateway_api.ResponseHeader.req_id', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gw_id', full_name='wirepas.proto.gateway_api.ResponseHeader.gw_id', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sink_id', full_name='wirepas.proto.gateway_api.ResponseHeader.sink_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='res', full_name='wirepas.proto.gateway_api.ResponseHeader.res', index=3,
      number=4, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=224,
)


_EVENTHEADER = _descriptor.Descriptor(
  name='EventHeader',
  full_name='wirepas.proto.gateway_api.EventHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gw_id', full_name='wirepas.proto.gateway_api.EventHeader.gw_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sink_id', full_name='wirepas.proto.gateway_api.EventHeader.sink_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='event_id', full_name='wirepas.proto.gateway_api.EventHeader.event_id', index=2,
      number=3, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=226,
  serialized_end=289,
)


_FIRMWAREVERSION = _descriptor.Descriptor(
  name='FirmwareVersion',
  full_name='wirepas.proto.gateway_api.FirmwareVersion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='major', full_name='wirepas.proto.gateway_api.FirmwareVersion.major', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='minor', full_name='wirepas.proto.gateway_api.FirmwareVersion.minor', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='maint', full_name='wirepas.proto.gateway_api.FirmwareVersion.maint', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dev', full_name='wirepas.proto.gateway_api.FirmwareVersion.dev', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=291,
  serialized_end=366,
)

_RESPONSEHEADER.fields_by_name['res'].enum_type = error__pb2._ERRORCODE
DESCRIPTOR.message_types_by_name['RequestHeader'] = _REQUESTHEADER
DESCRIPTOR.message_types_by_name['ResponseHeader'] = _RESPONSEHEADER
DESCRIPTOR.message_types_by_name['EventHeader'] = _EVENTHEADER
DESCRIPTOR.message_types_by_name['FirmwareVersion'] = _FIRMWAREVERSION
DESCRIPTOR.enum_types_by_name['OnOffState'] = _ONOFFSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestHeader = _reflection.GeneratedProtocolMessageType('RequestHeader', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTHEADER,
  __module__ = 'wp_global_pb2'
  # @@protoc_insertion_point(class_scope:wirepas.proto.gateway_api.RequestHeader)
  ))
_sym_db.RegisterMessage(RequestHeader)

ResponseHeader = _reflection.GeneratedProtocolMessageType('ResponseHeader', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSEHEADER,
  __module__ = 'wp_global_pb2'
  # @@protoc_insertion_point(class_scope:wirepas.proto.gateway_api.ResponseHeader)
  ))
_sym_db.RegisterMessage(ResponseHeader)

EventHeader = _reflection.GeneratedProtocolMessageType('EventHeader', (_message.Message,), dict(
  DESCRIPTOR = _EVENTHEADER,
  __module__ = 'wp_global_pb2'
  # @@protoc_insertion_point(class_scope:wirepas.proto.gateway_api.EventHeader)
  ))
_sym_db.RegisterMessage(EventHeader)

FirmwareVersion = _reflection.GeneratedProtocolMessageType('FirmwareVersion', (_message.Message,), dict(
  DESCRIPTOR = _FIRMWAREVERSION,
  __module__ = 'wp_global_pb2'
  # @@protoc_insertion_point(class_scope:wirepas.proto.gateway_api.FirmwareVersion)
  ))
_sym_db.RegisterMessage(FirmwareVersion)


# @@protoc_insertion_point(module_scope)
